# Generated by Django 4.1.7 on 2024-12-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_png_alter_category_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='png',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='value_name_az',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='value_name_en',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='value_name_es',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='value_name_ru',
        ),
    ]
